/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.uv.programa07cc;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Itzel Rios
 */

public class ProductoGUI extends javax.swing.JInternalFrame {
    DefaultTableModel dtm= new DefaultTableModel();
    DAOVenta dao=new DAOVenta();
    List<DetalleVenta> productos=new ArrayList<>();
    /**
     * Creates new form VentaProductoGUI
     */
    public ProductoGUI() {
        initComponents();
        String [] titulo= new String[]{"ID","Cantidad","Descripcion","Precio","subtotal","IdVenta"};
        dtm.setColumnIdentifiers(titulo);
        tblReg.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBrVenta = new javax.swing.JButton();
        btnAgrVenta = new javax.swing.JButton();
        txtDescripcion = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btnAgrProd = new javax.swing.JButton();
        txtIdVenta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnListProds = new javax.swing.JButton();
        btnListVent = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblReg = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setClosable(true);
        setTitle("Catalogo de Productos");

        jLabel1.setText("Id Venta: ");

        btnBrVenta.setText("Borrar Venta");
        btnBrVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrVentaActionPerformed(evt);
            }
        });

        btnAgrVenta.setText("Agregar Venta");
        btnAgrVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrVentaActionPerformed(evt);
            }
        });

        btnAgrProd.setText("Agregar Producto");
        btnAgrProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrProdActionPerformed(evt);
            }
        });

        jLabel2.setText("Descripcion: ");

        jLabel3.setText("Cantidad: ");

        jLabel4.setText("Precio: ");

        btnListProds.setText("Lista Productos");
        btnListProds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListProdsActionPerformed(evt);
            }
        });

        btnListVent.setText("Lista Ventas");
        btnListVent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListVentActionPerformed(evt);
            }
        });

        tblReg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblReg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPrecio)
                                .addComponent(txtCantidad)
                                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnListVent)
                        .addGap(38, 38, 38)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListProds, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAgrProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBrVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgrVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgrProd)
                    .addComponent(txtIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnBrVenta)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgrVenta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListVent)
                    .addComponent(btnListProds))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrVentaActionPerformed
        if(txtIdVenta.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Escribar el id de la venta!!");
        }
        else{
            int id= Integer.parseInt(txtIdVenta.getText());
            boolean res=dao.delete(id);
            if(res){
                JOptionPane.showMessageDialog(null, "Se ha borrado la venta");
                this.txtIdVenta.setText("");
                this.txtCantidad.setText("");
                this.txtDescripcion.setText("");
                this.txtPrecio.setText("");
            }
            else{
                JOptionPane.showMessageDialog(null, "No existe la venta");
            }
        }
    }//GEN-LAST:event_btnBrVentaActionPerformed

    private void btnAgrVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrVentaActionPerformed
        Venta vent;
        Date fecha= Date.from(Instant.now());
        if(productos.isEmpty()){
            JOptionPane.showMessageDialog(null, "No existen productos para la venta!!");
        }
        else{
            vent = new Venta();
            vent.setFecha(new java.sql.Date(fecha.getTime()));
            double monto = 0;
            for (DetalleVenta producto : productos) {
                producto.setVenta(vent);
                monto = monto + producto.getSubtotal();
                vent.getDetalle().add(producto);
            }
            vent.setMonto(monto);
            if (dao.create(vent) != null) {
                if (dtm.getRowCount() > 0) {
                    for (int i = dtm.getRowCount() - 1; i > -1; i--) {
                        dtm.removeRow(i);
                    }
                }
                JOptionPane.showMessageDialog(null, "Se agrego correctamente");
                this.txtCantidad.setText("");
                this.txtDescripcion.setText("");
                this.txtPrecio.setText("");
                for (DetalleVenta p : vent.getDetalle()) {
                    dtm.addRow(new Object[]{
                        String.valueOf(p.getIdProducto()), String.valueOf(p.getCantidad()), String.valueOf(p.getDescripcion()), String.valueOf(p.getPrecio()), String.valueOf(p.getSubtotal()), String.valueOf(vent.getIdVenta())
                    });
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error al agregar");
            }
        }
    }//GEN-LAST:event_btnAgrVentaActionPerformed

    private void btnAgrProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrProdActionPerformed
        if(txtCantidad.getText().isEmpty()||txtDescripcion.getText().isEmpty()||txtPrecio.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Algun campo esta vacio!!!");
        }
        else{
            if (dtm.getRowCount() > 0) {
                for (int i = dtm.getRowCount() - 1; i > -1; i--) {
                    dtm.removeRow(i);
                }
            }
            dtm = new DefaultTableModel();
            String[] titulo = new String[]{"ID", "Cantidad", "Descripcion", "Precio", "subtotal", "IdVenta"};
            dtm.setColumnIdentifiers(titulo);
            tblReg.setModel(dtm);
            double cant = Double.parseDouble(txtCantidad.getText());
            double prec= Double.parseDouble(txtPrecio.getText());
            double subtotal=cant*prec;
            DetalleVenta det= new DetalleVenta();
            det.setCantidad(cant);
            det.setDescripcion(txtDescripcion.getText());
            det.setPrecio(prec);
            det.setSubtotal(subtotal);
            dtm.addRow(new Object[]{"",txtCantidad.getText(),txtDescripcion.getText(),txtPrecio.getText(),String.valueOf(subtotal),""});
            productos.add(det);
            this.txtCantidad.setText("");
            this.txtDescripcion.setText("");
            this.txtPrecio.setText("");
        }

    }//GEN-LAST:event_btnAgrProdActionPerformed

    private void btnListProdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListProdsActionPerformed
        // TODO add your handling code here:
        dtm= new DefaultTableModel();
        String [] titulo= new String[]{"ID","Cantidad","Descripcion","Precio","subtotal","IdVenta"};
        dtm.setColumnIdentifiers(titulo);
        tblReg.setModel(dtm);
        List<Venta> ventas=dao.findAll();
        for (Venta venta : ventas) {
            for (DetalleVenta p : venta.getDetalle()) {
                dtm.addRow(new Object[]{
                    String.valueOf(p.getIdProducto()),String.valueOf(p.getCantidad()),String.valueOf(p.getDescripcion()),String.valueOf(p.getPrecio()),String.valueOf(p.getSubtotal()),String.valueOf(venta.getIdVenta())
                });
            }
        }
    }//GEN-LAST:event_btnListProdsActionPerformed

    private void btnListVentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListVentActionPerformed
        dtm= new DefaultTableModel();
        String [] titulo= new String[]{"Id Venta","Fecha","Monto"};
        dtm.setColumnIdentifiers(titulo);
        tblReg.setModel(dtm);
        List<Venta> ventas=dao.findAll();
        for (Venta venta : ventas) {
            dtm.addRow(new Object[]{
                String.valueOf(venta.getIdVenta()),String.valueOf(venta.getFecha()),String.valueOf(venta.getMonto())
            });
        }
    }//GEN-LAST:event_btnListVentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgrProd;
    private javax.swing.JButton btnAgrVenta;
    private javax.swing.JButton btnBrVenta;
    private javax.swing.JButton btnListProds;
    private javax.swing.JButton btnListVent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tblReg;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIdVenta;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
